### ISSUE TITLE
[UX Review] Groups - Global search

### ISSUE THREAD

**Issue by yih-wang** [keycloak/keycloak-admin-ui#692]
These issues haven't been addressed yet. @edewit 

1. A breadcrumb is missing so I can't find a way to return to the group list. Reference the design here - https://marvelapp.com/prototype/228971ig/screen/79872064
![image](https://user-images.githubusercontent.com/23331885/121533726-25211500-ca33-11eb-86ff-97339270e4a9.png)

2. This page needs to be updated to align with the design - https://marvelapp.com/prototype/228971ig/screen/79872065
![image](https://user-images.githubusercontent.com/23331885/121534013-69141a00-ca33-11eb-9c03-1bb1de7bbeaa.png)

**Comment by jonkoops** [comment]
@yih-wang I am taking a look at these issues. For #1 I cannot reproduce the issue, perhaps it has been fixed in the meantime? Could you give me a reproducible scenario?

For #2, what parts of the design are missing exactly? I see that the path is no longer displayed at all for example.

**Comment by yih-wang** [comment]
@jonkoops 

> For nr. 1 I cannot reproduce the issue, perhaps it has been fixed in the meantime? Could you give me a reproducible scenario?

Yes, I think it's been fixed, but the breadcrumb is still not correct. It should be Groups > Search group (align with the option name). Also I'm wondering whether the header should also be aligned with the option name - that is what we usually do. So the Search for groups can be changed to Search group. What do you think?
![image](https://user-images.githubusercontent.com/23331885/128658648-ccf1cc22-49a5-4b86-87ed-4dd0541c6433.png)

> For nr. 2, what parts of the design are missing exactly? I see that the path is no longer displayed at all for example.

I've checked the latest version of the search result screen. The padding is not correct. So the comparison between the search screen of the Groups and Users.
![image](https://user-images.githubusercontent.com/23331885/128658930-f9345f0c-b8e9-4bf1-ab30-df7d3245940a.png)
![image](https://user-images.githubusercontent.com/23331885/128659034-9c1f7c37-971f-4147-826a-8e76af91709d.png)

A new issue I found is after I search for something, a new level is added to the breadcrumb, which is not necessary. In the screenshot above, the breadcrumb should still be "Groups > Search group" instead of "Search > Search groups > Group details"
